### ISSUE TITLE
ESP8266 compatible

### ISSUE THREAD

**Issue by MagnusPer** [Adminius/DimmerControl#1]
Found this intressting project which I want to try out.  My plan is to integrate a dimmer using a NodeMCU (esp8266) with my home automation hub [Homey](https://www.athom.com/en/). The LEDs I want to control is 12VDC mounted in my kitchen and today contoled by [Nexa M-Spot](https://www.nexa.se/vara-produkter/system-nexa/mottagare-dimmers/mspot-12-24-v)

Before starting of  I have some questions.

1.  Any specific adaptions in the code needed for NodeMCU more than pinout
2.  What PWM frequency is used, didn´t find this easily in the code
3.  Do you have a hardware sketch example with needed MOSFET driver etc.

Thanks in advice!

**Comment by Adminius** [comment]
Hi,
there is nothing board specific. Each board can work with this library.
This library doesn't control PWM frequency. It uses any kind of PWM implementation (e.g. analogWrite)
Mosfet: IRLZ44N is a good one. [Schematic](https://iot-playground.com/images/articles/058/IRLZ44N.png)

**Comment by MagnusPer** [comment]
I realized that after closer look in the code, however I try this library as a base and add my own PWM implementation. Also thanks for the example schematic.
