### ISSUE TITLE
Last value stored

### ISSUE THREAD

**Issue by MagnusPer** [Adminius/DimmerControl#2]
[**Feature Request**]
Add a possibility to use "last stored value" on the next ON command. This for the purpose to go back to the stored dimlevel next time.

**Comment by Adminius** [comment]
Permanent: https://github.com/Adminius/DimmerControl/blob/master/examples/DimmerControl/DimmerControl.ino#L18

Temporarily:
```byte lastValue = 0; //holds last value```

and then use something like this (https://github.com/Adminius/DimmerControl/blob/master/examples/One_button_dimmer/One_button_dimmer.ino#L40-L46)
```
if(dimDirection){
        led.taskNewValue(lastValue); //turn on with last "on" value
        dimDirection = false;
}else{
        lastValue = led.getCurrentValue(); //save last "on" value
        led.taskDimDown();
        dimDirection = true;
}
```

**Comment by MagnusPer** [comment]
Thank you for the tips, works perfect!
