### ISSUE TITLE
Customized fade curve

### ISSUE THREAD

**Issue by MagnusPer** [Adminius/DimmerControl#3]
[**Feature Request**]
Add the possibility to use a customized fade curve since a strict linear 0-255 [0-100%] is not represented in a good way for the human eyes.

A colleague of my has used this fade algorithm for a better experience. 

const unsigned char ucLinear[MAX_LINEAR] = { 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,  4, 4, 4, 5, 5, 6, 6, 7, 8,  8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 20, 21, 23, 26, 28, 31, 33, 36, 40, 43, 47, 52, 56, 62, 67, 73, 80, 87, 95, 104, 114, 124, 135, 148, 161, 176, 192, 210, 229, 250}

![fade curve](https://user-images.githubusercontent.com/35903236/48465797-4a4e3800-e7e4-11e8-808f-3545deabebb2.JPG)

**Comment by Adminius** [comment]
Because of "customzing" i don't have any special function for it.
But you can still use it:

instead of https://github.com/Adminius/DimmerControl/blob/master/examples/DimmerControl/DimmerControl.ino#L5-L7

```
const unsigned char ucLinear[MAX_LINEAR] = 
{ 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 
4, 4, 4, 5, 5, 6, 6, 7, 8, 8, 9, 10, 11, 12, 13, 14, 
15, 17, 18, 20, 21, 23, 26, 28, 31, 33, 36, 40, 
43, 47, 52, 56, 62, 67, 73, 80, 87, 95, 104, 114, 
124, 135, 148, 161, 176, 192, 210, 229, 250};


void setValue(byte step){
    analogWrite(LED_BUILTIN, ucLinear[value]);
}
```

**Comment by MagnusPer** [comment]
Thank you, works much better now.
I generated the lookup table including values from this site [Linear LED PWM](https://jared.geek.nz/2013/feb/linear-led-pwm)
