### ISSUE TITLE
Clarification needed of some of the dimmer functions

### ISSUE THREAD

**Issue by MagnusPer** [Adminius/DimmerControl#4]
Can you please clarify the meaning and the usage for the functions below, thanks!

updateAvailable()
resetUpdateFlag()
taskStop()
isBusy()

**Comment by Adminius** [comment]
**updateAvailable()**
if you use taskDimUp or taskDimDown it can take longer between start and stop this action. it make sence to inform user about current percentage. around all 10% updateAvailable()==true => send an update to user. updateAvailable() is also *true*, if any task* is ready after execution.

**resetUpdateFlag()**
updateAvailable() will stay *true*, until you call resetUpdateFlag(). 

**taskStop()**
you can stop the execution of any task*-function with taskStop() within execution

**isBusy()**
if some of task*-functions is on going, isBusy is true.
